# Generated by Django 3.1.1 on 2020-09-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.IntegerField()),
                ('design', models.IntegerField()),
                ('machine_learning', models.IntegerField()),
                ('statistics', models.IntegerField()),
                ('deep_learning', models.IntegerField()),
                ('algorithm', models.IntegerField()),
                ('nlp', models.IntegerField()),
                ('data_score', models.IntegerField()),
                ('modeling_score', models.IntegerField()),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to='team_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_hearts', models.IntegerField()),
                ('web_hearts', models.IntegerField()),
                ('design_hearts', models.IntegerField()),
                ('modeling_hearts', models.IntegerField()),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='team_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField()),
                ('economy', models.IntegerField()),
                ('culture_art', models.IntegerField()),
                ('education', models.IntegerField()),
                ('society', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain', to='team_app.customer')),
            ],
        ),
    ]
